#!/bin/bash

docker build --build-arg CLUSTER_NAME=jsquad --build-arg CLUSTER_API_PORT=6443 --build-arg LOAD_BALANCER_PORTS="80;443" \
--build-arg INSTALL_EXTRA_PACKAGES_COMMANDS="helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx \
&& helm install my-nginx ingress-nginx/ingress-nginx" .